---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sentry-kafka
  namespace: sentry
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: persistent-claim
      class: yc-network-ssd
      size: 30Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
